"""Document stage: DOCUMENTING -> CODE_REVIEW | DELIVERABLE.

Inspects the implementation diff and, when the change is user-facing,
updates the relevant documentation files. For internal-only changes
(pure refactors, bug fixes with no doc impact) this stage is a no-op
and passes straight through.

The doc agent runs with warn-and-pass semantics: if it raises an
exception the ticket still progresses — losing a finished
implementation over a doc-update hiccup is the wrong trade.
"""

from __future__ import annotations

import logging
import random
import subprocess
import time
from pathlib import Path
from typing import Any

from ..agents.documenting import DocClassifierResult, DocResult
from ..config import target_branch_for
from ..core.models import Ticket
from ..core.states import State
from ..notify import send_notification
from ..vcs import git_ops
from ._implemented_repos import combined_diff, implemented_repos
from .base import Outcome, Stage, StageContext

log = logging.getLogger("robotsix_mill.stages.document")

# .md files excluded from mdformat reformatting (mirrors the pre-commit
# hook excludes — CHANGELOG.md is generated by the release workflow,
# changelog fragments are auto-generated one-liners).
_MDFORMAT_EXCLUDE_PREFIXES = ("CHANGELOG.md", "changelog.d/")

# Usage-limit failures are per-run budget caps, not invalid requests: a
# fresh agent run resets the budget, so a short exponential backoff retry
# is worthwhile before the stage falls back to its warn-and-pass note.
_DOC_AGENT_RETRY_ATTEMPTS = 3
_DOC_AGENT_BACKOFF_BASE = 2.0
_DOC_AGENT_BACKOFF_CAP = 30.0


def _is_usage_limit_error(exc: BaseException) -> bool:
    """Return True when *exc* is a usage/rate-limit failure worth retrying.

    Walks the ``__cause__``/``__context__`` chain so a wrapped exception
    (e.g. pydantic-ai ``UsageLimitExceeded`` surfaced through a runner) is
    still recognised. Matches the class-name/message signatures the doc
    agent's transports surface when a request/usage budget is exhausted.
    """
    seen: set[int] = set()
    cur: BaseException | None = exc
    while cur is not None and id(cur) not in seen:
        seen.add(id(cur))
        name = type(cur).__name__.lower()
        text = str(cur).lower()
        if (
            "usagelimitexceeded" in name
            or "claudesdkusageexhaustederror" in name
            or "rate limit" in text
            or "usage limit" in text
            or "request limit" in text
            or "429" in text
        ):
            return True
        cur = cur.__cause__ or cur.__context__
    return False


def _run_mdformat_on_changed_md_files(repo_dir: Path) -> None:
    """Run ``mdformat`` on every changed ``.md`` file in *repo_dir*.

    Finds ``.md`` files that have working-tree changes (the doc agent's
    edits) and runs canonical formatting on them so the commit lands
    clean without a CI auto-fix round-trip.  Mirrors the repo's
    pre-commit hook config (``--number --wrap 100``) and excludes the
    same paths (``CHANGELOG.md``, ``changelog.d/``).

    Never raises — a missing or broken ``mdformat`` must not block the
    stage.
    """
    # --- 1. Discover changed .md files ---
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only"],  # noqa: S607
            capture_output=True,
            text=True,
            cwd=repo_dir,
            check=True,
        )
    except subprocess.CalledProcessError:
        log.warning("mdformat: git diff failed — skipping")
        return

    md_files: list[str] = []
    for raw in result.stdout.strip().split("\n"):
        path = raw.strip()
        if not path or not path.endswith(".md"):
            continue
        if path.startswith(_MDFORMAT_EXCLUDE_PREFIXES):
            continue
        md_files.append(path)

    if not md_files:
        return

    # --- 2. Run mdformat ---
    # Prefer ``uv run mdformat`` (ticket-recommended convention), fall
    # back to ``python3 -m mdformat`` when the package is installed
    # directly.  Both accept the same CLI.
    args = ["--number", "--wrap", "100"]
    for cmd_templ in (
        ["uv", "run", "mdformat", *args],
        ["python3", "-m", "mdformat", *args],
    ):
        try:
            subprocess.run(  # noqa: S603
                [*cmd_templ, *md_files],
                cwd=repo_dir,
                check=True,
                capture_output=True,
                text=True,
            )
            log.info(
                "mdformat: formatted %d .md file(s) in %s",
                len(md_files),
                repo_dir,
            )
            return
        except subprocess.CalledProcessError as exc:
            log.debug("mdformat via %s failed: %s", cmd_templ[0], exc.stderr.strip())
        except FileNotFoundError:
            log.debug("mdformat: %s not available", cmd_templ[0])

    log.debug("mdformat: no available runner — skipping")


class DocumentStage(Stage):  # type: ignore[misc]  # Stage is from untyped robotsix_mill
    """Update project documentation from the implemented code changes."""

    name = "document"
    input_state = State.DOCUMENTING
    traced = True

    def run(self, ticket: Ticket, ctx: StageContext) -> Outcome:
        """Run the documentation agent against the post-implement clone."""
        s = ctx.settings

        ws = ctx.service.workspace(ticket)

        # Resolve the implemented clone(s) — single-repo (ws.dir/"repo")
        # or meta multi-repo (ws.dir/"repos/<id>" + touched_repos.json).
        repos = implemented_repos(ws, s, ticket)
        if not repos:
            return Outcome(
                State.BLOCKED,
                "no repository clone (re-run implement)",
            )

        target_branch = target_branch_for(s, ctx.repo_config)

        # Primary clone roots the doc agent's file tools; the rest (for a
        # multi-repo ticket) are passed as extra_roots so cross-repo
        # reads resolve. The combined diff fetches each repo with a
        # freshly-minted token for its own forge.
        repo_dir = repos[0].repo_dir
        extra_roots = [r.repo_dir for r in repos[1:]] or None

        try:
            diff = combined_diff(s, ctx.repo_config, repos, target_branch)
        except Exception as e:
            from ..runtime.transient_errors import reraise_if_transient
            from ..vcs.git_ops import redact_credentials

            reraise_if_transient(e)
            # str(CalledProcessError) reprs the full argv — including
            # the tokenized fetch URL. Redact before it hits the note.
            return Outcome(
                State.BLOCKED,
                f"failed to compute diff: {redact_credentials(str(e))}",
            )

        # Empty diff → nothing to document, pass through.
        if not diff.strip():
            log.info("%s: empty diff — no documentation needed", ticket.id)
            return Outcome(
                State.DELIVERABLE,
                "empty diff (no documentation needed)",
            )

        # Deterministic short-circuit: when every modified file is a
        # documentation or config path (.md extension or under docs/),
        # skip the classifier + doc agent — the doc agent would produce
        # only a recommendation anyway.
        modified_paths = git_ops._paths_from_diff(diff)
        if modified_paths and all(
            p.endswith(".md") or p.startswith("docs/") for p in modified_paths
        ):
            log.info(
                "%s: doc-only diff (%d paths) — skipping doc agent",
                ticket.id,
                len(modified_paths),
            )
            return Outcome(
                State.DELIVERABLE,
                "doc-only change (documentation/config files only; "
                "no doc agent needed)",
            )

        spec = ws.read_description()

        # --- Phase 1: cheap classifier gate ---
        # A single cheap LLM call decides whether the diff is user-facing.
        # Internal-only diffs skip the full (expensive) doc agent entirely.
        # Failure is non-blocking — we fall through to the full agent.
        try:
            classifier_result = self._run_doc_classifier(
                settings=s,
                diff=diff,
                spec=spec,
            )
            # The classifier verdict used to be posted as a comment;
            # it's an agent conclusion, not interaction with the
            # operator. Internal-only diffs short-circuit, so the
            # verdict lands in the next transition's note. For the
            # user-facing path the agent will still run and write a
            # doc artifact — the verdict is captured as a history
            # step event so it doesn't get lost.
            if not classifier_result.user_facing:
                log.info(
                    "%s: classifier says internal-only — skipping doc agent",
                    ticket.id,
                )
                return Outcome(
                    State.DELIVERABLE,
                    f"doc_classifier: {classifier_result.classification} — "
                    f"no user-facing changes; skipping doc agent",
                )
            ctx.service.add_step_event(
                ticket.id,
                f"doc_classifier: {classifier_result.classification} — "
                f"running full doc agent",
            )
        except Exception:
            log.warning(
                "%s: doc classifier failed — falling through to full doc agent",
                ticket.id,
                exc_info=True,
            )

        # Pre-load the modified files (parsed from the diff) plus
        # whichever top-level docs actually exist (README.md, AGENT.md)
        # so the doc agent doesn't have to read each file via a
        # separate round-trip. Same pattern review uses.
        preload_paths: list[str] = list(modified_paths)
        for doc_name in ("README.md", "AGENT.md"):
            if doc_name not in preload_paths and (repo_dir / doc_name).exists():
                preload_paths.append(doc_name)

        # --- Phase 2: full documentation agent ---
        # Usage-limit failures are retried with exponential backoff before
        # the stage gives up; a fresh agent run resets the per-run budget.
        try:
            doc_result = self._run_doc_agent_with_retry(
                settings=s,
                repo_dir=repo_dir,
                diff=diff,
                spec=spec,
                extra_roots=extra_roots,
                board_id=ctx.repo_config.board_id if ctx.repo_config else "",
                reference_files=preload_paths or None,
                ticket_id=ticket.id,
            )
        except Exception as e:
            from ..vcs.git_ops import redact_credentials

            redacted = redact_credentials(str(e))
            if _is_usage_limit_error(e):
                note = (
                    "doc agent skipped (non-blocking): persistent usage limit "
                    f"after {_DOC_AGENT_RETRY_ATTEMPTS} attempts — "
                    "documentation pass incomplete"
                )
            else:
                note = (
                    f"doc agent failed (non-blocking): {type(e).__name__}: {redacted}"
                )
            log.warning(
                "%s: doc agent failed — passing through (%s: %s)",
                ticket.id,
                type(e).__name__,
                redacted,
                exc_info=True,
            )
            send_notification(
                ticket,
                State.ERRORED,
                note,
                ctx.settings,
            )
            return Outcome(
                State.DELIVERABLE,
                note,
            )

        next_state = State.DELIVERABLE

        if doc_result.user_facing:
            try:
                if git_ops.has_changes(repo_dir):
                    # Post-process: run mdformat on every .md file the doc
                    # agent touched so the commit lands with canonical
                    # formatting — eliminates the CI auto-fix round-trip
                    # that would otherwise fire on every doc PR.
                    _run_mdformat_on_changed_md_files(repo_dir)

                    git_ops.commit_all(
                        repo_dir,
                        f"mill(docs): {ticket.title} ({ticket.id})",
                    )
                else:
                    # Recommendation-only deliverable: the agent reported a
                    # user-facing change but wrote no edits. Non-blocking —
                    # we still pass through (losing a finished implementation
                    # over a doc hiccup is the wrong trade) but flag it so
                    # retrospect/operators can see the gap.
                    log.warning(
                        "%s: doc agent reported user_facing=True but wrote no "
                        "edits — recommendation-only doc deliverable",
                        ticket.id,
                    )
                    ctx.service.add_step_event(
                        ticket.id,
                        "doc agent: recommendation-only doc deliverable "
                        "(user_facing=True but no edits applied)",
                    )
            except Exception:
                log.warning(
                    "%s: doc commit failed — passing through",
                    ticket.id,
                    exc_info=True,
                )
            return Outcome(next_state, doc_result.summary)

        return Outcome(next_state, "no user-facing changes (internal-only)")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _run_doc_agent(
        self,
        *,
        settings: Any,
        repo_dir: Path,
        diff: str,
        spec: str,
        extra_roots: list[Path] | None = None,
        board_id: str = "",
        reference_files: list[str] | None = None,
    ) -> DocResult:
        """Run the documentation agent to classify the diff and update docs.

        Returns a ``DocResult`` with ``user_facing`` (bool) and ``summary``
        (str describing what was updated or that no changes were needed).
        """
        from ..agents.documenting import run_doc_agent

        return run_doc_agent(
            settings=settings,
            repo_dir=repo_dir,
            diff=diff,
            spec=spec,
            extra_roots=extra_roots,
            board_id=board_id,
            reference_files=reference_files,
        )

    def _run_doc_agent_with_retry(
        self,
        *,
        settings: Any,
        repo_dir: Path,
        diff: str,
        spec: str,
        extra_roots: list[Path] | None = None,
        board_id: str = "",
        reference_files: list[str] | None = None,
        ticket_id: str = "",
        sleep: Any | None = None,
    ) -> DocResult:
        """Run the doc agent, retrying usage/rate-limit failures.

        A usage-limit failure means the agent exhausted its per-run request
        budget, not that the request is invalid; each fresh agent run gets
        a fresh budget, so a short exponential-backoff retry usually
        finishes the documentation pass.  Any other exception re-raises
        immediately so the stage keeps its warn-and-pass behaviour for
        non-transient failures.
        """
        if sleep is None:
            sleep = time.sleep
        last_exc: Exception | None = None
        for attempt in range(_DOC_AGENT_RETRY_ATTEMPTS):
            try:
                return self._run_doc_agent(
                    settings=settings,
                    repo_dir=repo_dir,
                    diff=diff,
                    spec=spec,
                    extra_roots=extra_roots,
                    board_id=board_id,
                    reference_files=reference_files,
                )
            except Exception as e:
                last_exc = e
                if not _is_usage_limit_error(e):
                    raise
                if attempt == _DOC_AGENT_RETRY_ATTEMPTS - 1:
                    break
                delay = min(
                    _DOC_AGENT_BACKOFF_CAP,
                    _DOC_AGENT_BACKOFF_BASE * (2**attempt),
                )
                delay += random.uniform(0, delay / 2)  # noqa: S311  # jitter
                log.warning(
                    "%s: doc agent hit a usage limit (%s) — retrying in "
                    "%.1fs (attempt %d/%d)",
                    ticket_id,
                    type(e).__name__,
                    delay,
                    attempt + 2,
                    _DOC_AGENT_RETRY_ATTEMPTS,
                )
                sleep(delay)
        if last_exc is None:  # pragma: no cover
            raise RuntimeError("doc agent retry loop exhausted without an error")
        raise last_exc

    def _run_doc_classifier(
        self,
        *,
        settings: Any,
        diff: str,
        spec: str,
    ) -> DocClassifierResult:
        """Run the cheap classifier gate (user-facing vs internal-only).

        Returns a ``DocClassifierResult`` with ``user_facing`` (bool) and
        ``classification`` (human-readable one-liner).
        """
        from ..agents.documenting import run_doc_classifier

        return run_doc_classifier(
            settings=settings,
            diff=diff,
            spec=spec,
        )
