"""Every exported settings-schema property must carry a description.

Guards the settings-UI hover-help contract: the schema served at the
``GET /config`` ``schema`` key (and generated by
:func:`robotsix_chat.config.schema_docs.apply_property_descriptions`) must
leave no property without a non-empty ``description``.
"""

from __future__ import annotations

from typing import Any

from robotsix_config import config_schema

from robotsix_chat.chat.server.routes.config import _get_schema
from robotsix_chat.config import Settings
from robotsix_chat.config.schema_docs import (
    _parse_attributes,
    apply_property_descriptions,
)


def _missing_descriptions(schema: dict[str, Any]) -> list[str]:
    """Return dotted ``object.property`` paths for properties lacking a description."""
    missing: list[str] = []

    def check(owner: str, obj: dict[str, Any]) -> None:
        for name, prop in obj.get("properties", {}).items():
            if not isinstance(prop, dict):
                continue
            if not (prop.get("description") or "").strip():
                missing.append(f"{owner}.{name}")

    check("<root>", schema)
    for def_name, definition in schema.get("$defs", {}).items():
        if isinstance(definition, dict):
            check(def_name, definition)
    return missing


def test_exported_schema_has_description_on_every_property() -> None:
    """The schema served to the settings UI documents every property."""
    schema = _get_schema()
    assert _missing_descriptions(schema) == []


def test_apply_property_descriptions_fills_from_docstrings() -> None:
    """Running the filler over the raw schema documents every property."""
    raw = config_schema(Settings)
    # The raw schema has undocumented properties before the filler runs.
    assert _missing_descriptions(raw) != []
    filled = apply_property_descriptions(raw)
    assert _missing_descriptions(filled) == []


def test_parse_attributes_reads_multiline_entries() -> None:
    """The Attributes parser handles single- and multi-line field entries."""
    description = (
        "Some model summary.\n\n"
        "Attributes:\n"
        "    enabled: Master switch.\n"
        "    timeout: Per-request timeout\n"
        "        with a continuation line.\n"
    )
    attrs = _parse_attributes(description)
    assert attrs["enabled"] == "Master switch."
    assert attrs["timeout"] == "Per-request timeout with a continuation line."
