#!/usr/bin/env python3
r"""Post-deploy defacement detection -- HTTP probe for CI/CD pipelines.

Performs an HTTPS GET against a public URL, follows redirects, and checks
the response body for known defacement indicators (attacker signatures,
unexpected CMS installs, generic error pages).  Exits 0 when the page is
clean (no defacement detected); exits 1 when any defacement indicator is
found.  Designed as a zero-dependency-beyond-httpx post-deploy gate that
any CI pipeline can invoke.

Usage::

    uv run python scripts/http_probe_cli.py https://www.example.com
    uv run python scripts/http_probe_cli.py \\
        --expect-contains "My Brand" \\
        --expect-absent "graybyte" "Google Gemini \u2013 AI" \\
        https://www.example.com

Environment variables::

    HTTP_PROBE_PATTERNS_ABSENT   JSON list of defacement substrings (merged
                                with CLI args).  E.g.:
                                '["graybyte", "WordPress"]'
    HTTP_PROBE_TIMEOUT           Request timeout in seconds (default 10).
"""

from __future__ import annotations

import json
import os
import sys
import time as _time
from typing import NoReturn

import httpx

# ---------------------------------------------------------------------------
# Default defacement indicators -- update these as new attacker signatures
# surface.  Case-insensitive substring match against the response body.
# ---------------------------------------------------------------------------
DEFAULT_DEFACEMENT_PATTERNS: list[str] = [
    # Attack group / individual signatures
    "graybyte",
    # AI scraped / auto-generated landing pages
    "Google Gemini \u2013 AI",
    "Generated by ChatGPT",
    "AI-generated content",
    # Fresh CMS installs (attacker replaced the site)
    "Welcome to WordPress",
    "Just another WordPress site",
    "Powered by WordPress",
    "WordPress &rsaquo; Installation",
    "WordPress &rsaquo; Error",
    "Drupal installation",
    "Joomla! - Installation",
    # Generic server error / directory listing
    "Index of /",
    "Error establishing a database connection",
    "Service Unavailable",
]


def _env_patterns() -> list[str]:
    """Read extra defacement patterns from ``HTTP_PROBE_PATTERNS_ABSENT``."""
    raw = os.environ.get("HTTP_PROBE_PATTERNS_ABSENT", "")
    if not raw:
        return []
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        print(
            f"http_probe_cli: invalid JSON in HTTP_PROBE_PATTERNS_ABSENT: {raw!r}",
            file=sys.stderr,
        )
        sys.exit(2)
    if not isinstance(parsed, list) or not all(isinstance(s, str) for s in parsed):
        print(
            "http_probe_cli: HTTP_PROBE_PATTERNS_ABSENT must be a JSON list of strings",
            file=sys.stderr,
        )
        sys.exit(2)
    return parsed


def _cli_args_absent() -> list[str]:
    """Extract ``--expect-absent`` values from remaining argv."""
    args: list[str] = []
    argv = sys.argv[1:]
    i = 0
    while i < len(argv):
        if argv[i] == "--expect-absent":
            i += 1
            if i >= len(argv):
                print(
                    "http_probe_cli: --expect-absent requires a value",
                    file=sys.stderr,
                )
                sys.exit(2)
            args.append(argv[i])
        elif argv[i].startswith("--expect-absent="):
            args.append(argv[i].split("=", 1)[1])
        else:
            # not our flag -- keep scanning for positional-flag mix
            pass
        i += 1
    return args


def _cli_args_contains() -> list[str]:
    """Extract ``--expect-contains`` values from remaining argv."""
    args: list[str] = []
    argv = sys.argv[1:]
    i = 0
    while i < len(argv):
        if argv[i] == "--expect-contains":
            i += 1
            if i >= len(argv):
                print(
                    "http_probe_cli: --expect-contains requires a value",
                    file=sys.stderr,
                )
                sys.exit(2)
            args.append(argv[i])
        elif argv[i].startswith("--expect-contains="):
            args.append(argv[i].split("=", 1)[1])
        i += 1
    return args


def _resolve_url() -> str:
    """Return the probe URL from CLI positional arguments."""
    argv = sys.argv[1:]
    for arg in argv:
        if not arg.startswith("-"):
            return arg
    print("http_probe_cli: missing URL argument", file=sys.stderr)
    print(
        "usage: http_probe_cli [--expect-contains STR]... [--expect-absent STR]... URL",
        file=sys.stderr,
    )
    sys.exit(2)
    return ""  # unreachable — satisfies static analysis that all paths return str


def main() -> NoReturn:
    """Run the HTTP probe and exit 0 (clean) or 1 (defacement detected)."""
    url = _resolve_url()
    expect_contains = _cli_args_contains()
    expect_absent = _cli_args_absent() + _env_patterns()

    if not expect_absent:
        # Use built-in defacement defaults when neither CLI nor env
        # provides patterns.
        expect_absent = list(DEFAULT_DEFACEMENT_PATTERNS)

    timeout = float(os.environ.get("HTTP_PROBE_TIMEOUT", "10"))

    result: dict = {
        "url": url,
        "final_url": url,
        "status_code": None,
        "response_time_ms": None,
        "body_snippet": "",
        "defacement_detected": False,
        "matched_patterns": [],
        "error": "",
    }

    try:
        with httpx.Client(timeout=timeout, follow_redirects=True) as client:
            start = _time.monotonic()
            resp = client.get(url)
            elapsed = (_time.monotonic() - start) * 1000.0

            result["final_url"] = str(resp.url)
            result["status_code"] = resp.status_code
            result["response_time_ms"] = round(elapsed, 1)
            result["body_snippet"] = resp.text[:2048]

            # Check defacement patterns
            body_lower = resp.text.lower()
            matched: list[str] = []
            for pattern in expect_absent:
                if pattern.lower() in body_lower:
                    matched.append(pattern)

            if matched:
                result["defacement_detected"] = True
                result["matched_patterns"] = matched

            # Check expect_contains
            missing_contains: list[str] = []
            for pattern in expect_contains:
                if pattern.lower() not in body_lower:
                    missing_contains.append(pattern)

            if missing_contains:
                result["defacement_detected"] = True
                result.setdefault("missing_expected", []).extend(missing_contains)

    except httpx.TimeoutException:
        result["error"] = f"Request timed out after {timeout}s"
        result["defacement_detected"] = True
    except Exception as exc:
        result["error"] = f"{type(exc).__name__}: {exc}"
        result["defacement_detected"] = True

    print(json.dumps(result, indent=2, ensure_ascii=False))

    if result["defacement_detected"]:
        if result.get("matched_patterns"):
            print(
                "\n::error::DEFACEMENT DETECTED --"
                f" matched patterns: {result['matched_patterns']}",
                file=sys.stderr,
            )
        if result.get("missing_expected"):
            print(
                f"\n::error::MISSING EXPECTED CONTENT: {result['missing_expected']}",
                file=sys.stderr,
            )
        if result.get("error"):
            print(
                f"\n::error::PROBE ERROR: {result['error']}",
                file=sys.stderr,
            )
        sys.exit(1)
    else:
        print("\n::notice::No defacement detected", file=sys.stderr)
        sys.exit(0)


if __name__ == "__main__":
    main()
